# wiscow-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiscow-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wiscow
  template:
    metadata:
      labels:
        app: wiscow
    spec:
      containers:
      - name: wiscow-container
        image: us-central1-docker.pkg.dev/focal-appliance-411112/ishu/static-site:sha256:b7741dc58e0a4c52920a54169870cfe010d1a8212f0a7c9216eb357136ec37a8
        ports:
        - containerPort: 4499

---
# wiscow-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: wiscow-service
spec:
  selector:
    app: wiscow
  ports:
    - protocol: TCP
      port: 4499
      targetPort: 4499
  type: NodePort
